# Permalinks
permalink:        pretty

collections:
  projects:
    output: true
  links:
    output: true
  music:
    output: true
  stories:
    output: true

defaults:
  - scope:
      path: "/wiki/*"
    values:
      layout: "wiki"
  - scope:
      path: "/notes/*"
    values:
      layout: "note"      